export const env = {
  AUTH_ZITADEL_ISSUER: process.env.AUTH_ZITADEL_ISSUER!,
  AUTH_ZITADEL_ID: process.env.AUTH_ZITADEL_ID!,
  AUTH_ZITADEL_SECRET: process.env.AUTH_ZITADEL_SECRET!,
  DATABASE_URL: process.env.DATABASE_URL!,
}
